dataset_name: "cars"
search_objective: "mse"
lower_is_better: true
task_description: "The task is to predict retail prices of cars based on a set of attributes of each car"
categorical_mask: [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]