dataset_name: "heart-statlog"
search_objective: "balanced_accuracy"
lower_is_better: false
task_description: "The task is to classify people as having heart disease or not based on a set of attributes"
categorical_mask: [0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1]